### ISSUE TITLE
[Feature Request] Network Drive (e.g. rclone) polling support

### ISSUE THREAD

**Issue by VP-EN** [RatingPosterDB/rpdb-folders#11]
**[Feature Request] Network Drive (e.g. rclone) polling support** .. 
as a way to look for newly created folders 😄 

**Is your feature request related to a problem? Please describe.**
Right now, the `rpdb-folders` doesn't recognize the new folders created by a network drive, mounted through [rclone](https://rclone.org/commands/rclone_mount/). 
Whenever rclone is polling for new changes in the mounted folders, `rpdb-folders` does not recognize them as new folders, and therefore won't add new posters (and/or backdrops) automatically. This results in the user having to do a manual full scan (which takes unnecessary API hits).

**Describe the solution you'd like**
Support for network drive "polling", so `rpdb-folders` will look for newly "discovered" (polled) folders, that wasn't present when the initial scan was done. 

**Additional context**
I know I mentioned this on reddit, but this seems more organized 👍

**Comment by jaruba** [comment]
This feature is now available with [v0.1.3](https://github.com/RatingPosterDB/rpdb-folders/releases/tag/v0.1.3)
