### ISSUE TITLE
[Feature Request] Adding more badges (quality, DoVi, etc)

### ISSUE THREAD

**Issue by VP-EN** [RatingPosterDB/rpdb-folders#12]
**[Feature Request] A "Fake 4k" / "Upscaled 4k" badge**
**[Feature Request] Adding more badges (quality, DoVi, etc)**

**Is your feature request related to a problem? Please describe.**
As of now, there are multiple badges available for certain tiers, which is awesome, and which I personally use for one of my 4K libraries.
But, as some of you might now, a lot of 4K movies are not "real 4k", but rather [upscaled 4K](https://real4kbluray.com/the-difference-between-fake-and-real-4k-movies/). 
 
**Describe the solution you'd like**
This is in nitpicky territory, but it would be nice to have the addition of a "Fake 4K" or "Upscaled 4K" badge to differentiate between the real 4K blurays and the ones that are "just" upscaled.
Again, this might be a minor thing, as it might [not matter that much](https://www.thatavdude.com/real-or-fake-4k/).

**Additional context**
Not sure what color it should be. The regular 4K badge is gold/yellow-ish colored, which fits the "proper 4k" category. Not sure what color the fake 4k / upscaled 4k badge should be.

**Edit/afterthought**: Maybe it should be named "2KDI", as it not as "hostile" sounding as fake.

**Comment by jaruba** [comment]
@VP-EN 

> The regular 4K badge is gold/yellow-ish colored, which fits the "proper 4k" category. Not sure what color the fake 4k / upscaled 4k badge should be.

Silver? Added both badges for comparison:

![4k-upscaled](https://user-images.githubusercontent.com/1777923/119707674-17309900-be64-11eb-8ed5-1fbc3f488637.jpg)

**Comment by jaruba** [comment]
To note, right now all video quality badges are gold though, it makes sense to make the lesser qualities silver though.. but I feel like 1080p should still be gold too as that can be the highest quality for some setups.. Even if upscaled 4K would be silver.

**Comment by VP-EN** [comment]
As yes that would be perfect

And yeah, I agree with keeping the 1080p gold :)! In my case, I keep seperate libraries (and folders) for 4K content and 1080p/720p

Now that we're discussing new badges, is it possible to add a "Dolby Vision" badge as well? Forgot about it, when I made the issue.

**Comment by jaruba** [comment]
Sure, I'll look into creating such a badge too.

**Comment by VP-EN** [comment]
You are my hero

**Comment by jaruba** [comment]
@VP-EN How about this?

![new-badge-test](https://user-images.githubusercontent.com/1777923/119764814-c730f100-beba-11eb-88a8-e9bc5b71ff9e.jpg)

**Comment by VP-EN** [comment]
That looks perfect!

**Comment by VP-EN** [comment]
Oh, thought of another useful badge while managing some folders.
The **4K WEB** release should have a seperate badge as well. Usually along the bitrate of a 2160p encode (non-remux). It would be nice as a complementary badge. Probably useful being in silver as well, as it'll probably work as a replacement for the REMUX badge.

**Comment by jaruba** [comment]
Sure, I'll look into it, but it will probably happen next week as I'll be away this weekend.

**Comment by VP-EN** [comment]
No worries, appreciate your help 😁

**Comment by VP-EN** [comment]
Come to think of it, the `4K (Upscaled)` could use an alternative in gold: `4K (2KDI)`. Then the user will have the choice between a grey and a gold one, with the wording sounding a bit different. This could be in the `Video Quality` badge-menu as well:
```
4K (Ultra HD)
4K (2KDI) [gold]
4K (Upscaled) [silver]
1080p (Full HD)
720p (HD)
2K (Quad HD)
5K (Ultra HD)
8K (Ultra HD)
```

**Comment by jaruba** [comment]
@VP-EN But 2KDI is 2048x1080, which means it's 2K (Quad HD) not 4K, right?

**Comment by VP-EN** [comment]
You're probably right. Initially I thought the 2KDI was the name/technique used to upscale 2K content to 4K, but it seems its just a term referring to the 2048x1080 resolution. 
Maybe just make the 4K Upscaled in gold as well as silver.

**Comment by jaruba** [comment]
> but it seems it's just a term referring to the 2048x1080 resolution.

The "DI" at the end means "Digital Intermediate", which basically means that the video includes black bars. I'm not sure if there's any reason to have a badge for it, because there are probably many that state 2K / 4K, have black bars and do not state DI. It's a useless thing mentioning that imo..

> Maybe just make the 4K Upscaled in gold as well as silver.

Sure, if you think there's a reason for that.

**Comment by VP-EN** [comment]
Having both silver and gold atleast let's Plex admins choose between them. Having the silver badge next to gold 4K badges might give the impression that it's of lesser quality / value.
As [the link](https://www.thatavdude.com/real-or-fake-4k/) in my OP states, it might not matter that much. 
Which makes having the gold badge available a nice alternative, if you don't want your users to think it's of lesser value, but let them know it's upscaled regardless.
Not sure if I make any sense, but I figure it's nice to have both choices available

**Comment by jaruba** [comment]
The new badges have been added to [v0.1.3](https://github.com/RatingPosterDB/rpdb-folders/releases/tag/v0.1.3)
