### ISSUE TITLE
[Feature Request] Individual badge selection for movie/series posters

### ISSUE THREAD

**Issue by VP-EN** [RatingPosterDB/rpdb-folders#13]
**[Feature Request] Individual badge selection for movie/series posters** 
Kind of related to https://github.com/RatingPosterDB/rpdb-folders/issues/12

**Is your feature request related to a problem? Please describe.**
I just realized it's not possible to edit the badges of individual posters. Right now it's possible to select badges, for each media folder selected. This mostly works fine. But in my case, the library can be somewhat mixed with 4K and the upcoming "4K Upscaled" and "Dolby Vision" badge(s).
It would be very help to "overwrite" individual movie (and/or series) posters with certain badges, e.g. "4K Upscaled" and "Dolby Vision".

**Describe the solution you'd like**
This could be a part of the `Edit Movie Poster` or `Edit Series Poster`, e.g.
1. Press `Edit Movie Poster`
2. Search for the movie folder, you want to edit
3. Select `Edit Badge(s) for this poster` or something similiar
4. Enter the same menu as `Add Badges / Label`, just for the selected poster

**Additional context**
Again, this would be helpful, as some movies are 4K Upscaled, and some have Dolby Vision. This would be an easier solution (or maybe just an alternative solution), than creating media folders for each and every category:
E.g. 1x 4K Upscaled library, 1x "Real" 4K library, 1x 4K Upscaled+Dolby Vision and 1x"Real" 4K+Dolby Vision library.'

Editing the individual posters seems easier to me atleast

**Edit**: Also thanks for all your work 😄 👍

**Comment by VP-EN** [comment]
Come to think of it, it might be easier sorting it through media folders.
I'll keep it open for now, it might be useful in some cases. E.g. A 2KDI/Upscaled movie, but with Dolby Vision or some weird combination

**Comment by jaruba** [comment]
This feature is now available with [v0.1.3](https://github.com/RatingPosterDB/rpdb-folders/releases/tag/v0.1.3)
