### ISSUE TITLE
Allow bars to be additions to the image rather than overlays

### ISSUE THREAD

**Issue by darthShadow** [RatingPosterDB/rpdb-folders#16]
Allow bars to be additions to the image rather than overlays so that the poster doesn't get covered due to too many badges.

**Comment by jaruba** [comment]
I don't believe that this is a good idea, posters have a very specific aspect ratio. All posters respect this aspect ratio and all apps presume this aspect ratio from posters, thus they dedicate a space for posters that respects this aspect ratio itself.

Adding bars above / under the posters would change the image aspect ratio which will make the apps remove parts of the poster from view, so it will most probably cut out either parts of the bars, the bars completely or parts of the poster.

So we can only overlay bars, we cannot extend the image outside of the presumed aspect ratio.

**Comment by darthShadow** [comment]
Possible to adjust the aspect ratios of the posters so that the overall aspect ratio, with the bars, still remains the same?

**Comment by jaruba** [comment]
the only way we could maintain the aspect ratio and the complete poster within an image is by reducing the overall size of the poster and centering it, which would create gaps on the left / right sides, here is an example:
<img width="250" alt="Screen Shot 2021-06-12 at 19 00 52" src="https://user-images.githubusercontent.com/1777923/121782170-eb761880-cbb0-11eb-9b73-db5d0f294a9c.png">

I don't think this is a good solution, in some cases on some devices the posters are already pretty small, this would make them much smaller.. and if we want the badges to be outside the posters too, that will make the space left for posters very small..

**Comment by darthShadow** [comment]
Alright, that makes sense, thanks. Closing this.
