### ISSUE TITLE
Allow specifying the percentage the badges and ratings bar

### ISSUE THREAD

**Issue by darthShadow** [RatingPosterDB/rpdb-folders#17]
The size of the badges and the rating bar should be adjustable as a percentage relative to their full size.

**Comment by darthShadow** [comment]
Hi, any idea how long this will take to add? I am really waiting on this to start replacing posters since otherwise, quite a few of them have their titles on the poster get covered fully by these bars because they occupy a significant percentage of the overall poster by default.

**Comment by jaruba** [comment]
@darthShadow so u want them to be smaller? would 70% of the current size be ok for ur needs?

**Comment by darthShadow** [comment]
Would it not be possible to make the percentage configurable or is that too much work on the image processors? I am asking for this since I am not sure how 70% would look and may decide to further change it later on

**Comment by jaruba** [comment]
I just doubt that anyone will ever need more than one more (smaller) size for badges. I think 70% should be acceptable for most cases, as smaller than that might be too small to see the badge accurately.

**Comment by darthShadow** [comment]
Sounds reasonable. Is there any way to compare before you go ahead and make that change? I assume this will be for both the badges and the ratings bar at the bottom?

**Comment by jaruba** [comment]
There have been others that requested smaller badges, but you are the only one that ever requested a smaller rating bar.

The rating bar is currently 9.8% of the height of the poster, anything smaller than that and the ratings would be very hard to see clearly in some scenarios, as the posters themselves can be small in some apps. (phones, but not only, for Plex's case the web version also has very small posters)

You can always edit the posters with the RPDB Folders app and choose a poster that shows the title in a different place, this is (in general) a better practice for reducing the impact of that.. But in the end there will always be such issues, we're overlaying things over an image, and the posters can be very different from one another, there is absolutely no way to avoid these elements going over parts of the title in all cases, even if the rating bar would be 5% of the height (and completely impossible to read) it will still happen.

**Comment by darthShadow** [comment]
I was mostly focused on TV displays but you make a good point about the posters on phones. Although I would still like the option to make them slightly smaller (75-80%), I can manage with only the badges being smaller.

**Comment by jaruba** [comment]
@darthShadow I made a new release that allows setting smaller badges, I tested with a smaller bar for ratings and there are too many posters that will still have cut off titles, I do not consider reducing the badge size a solution for this.

**Comment by darthShadow** [comment]
Np, thanks a lot for getting it resolved so quickly. Will just choose alternative posters as and when I see ones that have been cut off.
