### ISSUE TITLE
Additional Sources for Anime Ratings

### ISSUE THREAD

**Issue by darthShadow** [RatingPosterDB/rpdb-folders#18]
Add additional sources for Anime Ratings like MAL, AL etc.

**Comment by jaruba** [comment]
This is already planned, but it may take a long time as it is a complex / lengthy task.

**Comment by darthShadow** [comment]
No issues. Liked the ratings on https://anime-track.app and hence raised this request.

**Comment by jaruba** [comment]
I have added MAL ratings to all anime, these will show with the all poster types: `poster-default`, `poster-certs`, `poster-rt`, `poster-mc`, `textless-default`, `textless-certs`, `textless-rt`, `textless-mc`

For `-default`, `-certs` poster types, the rating orders are: mal, imdb, rt (+ mc is any rating is missing)

I have added a note about anime ratings in the api docs too: https://rpdb.docs.apiary.io/

I don't think I'll add AL and Kitsu, from my experience of monitoring the anime ratings for a long time, AL and Kitsu ratings are very very similar to the MAL rating, so IMDB / RT / MC are more valuable for anime imo.

**Comment by darthShadow** [comment]
Perfect, thanks a lot.
