### ISSUE TITLE
Poster localization

### ISSUE THREAD

**Issue by memnos** [RatingPosterDB/rpdb-folders#20]
Hello, 
i'd like to know if posters are also localized or are just in English.
For example i use emby and all posters, where available, now are in italian, what about if i use rpdb-folders?
Tnx

**Comment by jaruba** [comment]
Currently all posters are in english, and users have the ability of changing individual posters through the UI to national ones.

A setting for default poster language has been requested before and is a planned feature, my hopes are that I'll manage to add this feature by the end of the week.

**Comment by memnos** [comment]
You mean changing poster via Emby? But in this situation don't i loose ratings as the poster is changed?
Aren't ratings saved in the img file?

**Comment by jaruba** [comment]
No, I mean that the RPDB Folders app has a Web UI of it's own, which allows the customisation of posters by type, media folder, or individual posters.

Within the RPDB Folders app, you can search for particular posters and edit their underlying image, badges, etc. When editing a particular poster, for Tier 2+ there is an option to choose the poster (from any TMDB poster) and allows filtering the TMDB posters by language also.

**Comment by memnos** [comment]
OK, i should subscribe tier 2+ to have the possibility to choose Italian language, otherwise it is English poster?

Last question, posters with ratings are only seen in emby webui or also in all emby apps?

**Comment by jaruba** [comment]
In all apps (phone, web, desktop, etc.) for all media servers (Plex / Emby / Jellyfin / Kodi), for all users.

**Comment by memnos** [comment]
Tnx.
And for localized posters i need tier 2? Tier 1 is not enough?

**Comment by jaruba** [comment]
Tier 1 only supports default posters, Tier 2 is needed to choose custom TMDB posters. Also, you would need to use the RPDB Folders app to choose different posters, the media server plugins don't support this feature yet.

**Comment by memnos** [comment]
OK, tnx, now it is all clear.

**Comment by memnos** [comment]
I saw it has been committed "Settings for Default Poster Language"
When will it be available?

**Comment by jaruba** [comment]
I still have one more feature that I need to add before the release, and am working on adding localization and a few of the badges to the media server plugins too. I will tell u when it is ready.

**Comment by jaruba** [comment]
This feature is now available with RPDB Folders v0.1.4
