### ISSUE TITLE
Error: ENOENT

### ISSUE THREAD

**Issue by memnos** [RatingPosterDB/rpdb-folders#21]
I'v just bought a api key, i wrote a mail with this problem but i think it is better to write here.

The api works fine.

I'm using rpdb folders with windows and i have network folders mounted

I though it was all automatic, but i don't understand how to make it start.
I think i settled all up, but i don't know how to start scan and download posters with ratings.
I managed to scan manually a folder and select poster, but how to make i write the poster to the movie folder?

I have network folders mounted in windows.

Can you give me any suggestions?

In console i see this.

{ Error: ENOENT: no such file or directory, scandir 'Z:\Movies\12 anni schiavo (2013)'
    at Object.readdirSync (fs.js:790:3)
    at Object.fs.readdirSync (pkg/prelude/bootstrap.js:828:35)
    at getDirectories (C:\snapshot\rpdb-folders\index.js:0:0)
    at theseFolders.forEach.mediaFolder (C:\snapshot\rpdb-folders\index.js:0:0)
    at Array.forEach (<anonymous>)
    at startFetchingPosters (C:\snapshot\rpdb-folders\index.js:0:0)
    at app.get.passwordValid (C:\snapshot\rpdb-folders\index.js:0:0)
    at passwordValid (C:\snapshot\rpdb-folders\index.js:0:0)
    at app.get (C:\snapshot\rpdb-folders\index.js:0:0)
    at Layer.handle [as handle_request] (C:\snapshot\rpdb-folders\node_modules\express\lib\router\layer.js:95:5)
  errno: -4058,
  syscall: 'scandir',
  code: 'ENOENT',
  path: 'Z:\\Movies\\12 anni schiavo (2013)' }

**Comment by jaruba** [comment]
That error states that the folder does not exist when the app tries to read the files from inside that folder.

Try this:
- close the RPDB app
- ensure that the "Z" drive exists (that the network drive did not change the drive letter by any chance)
- delete this file: `%localappdata%\RPDB-Folders\config.json` (this file holds all ur current app settings)
- start RPDB Folders
- set ur settings again to ur preference
- add ur media folders (not direct movie folders)

**Comment by jaruba** [comment]
Closing this issue as the user that had this error has declined payment for the month and development should be directed towards active users.

This is the only case that had issues writing / reading files and folders from a network storage that I know of, which makes it an isolated case. If other users encounter it in the future I'll restart the investigation.

For historical purposes, the current research seemed to suggest that:
- the network drive letter could have changed in the meantime
- the application was running on a different Windows user or with UAC elevation; networks drives are relative to the Windows user, as this page explains: https://stackoverflow.com/questions/63849008/enoent-when-trying-to-access-network-share-via-drive-letter-in-windows

The discussions with the user that raised the issue seemed to suggest that this was not the case though, further investigation would of been required to resolve it.
