### ISSUE TITLE
Error: libnode.so.72 in linux

### ISSUE THREAD

**Issue by memnos** [RatingPosterDB/rpdb-folders#22]
In Ubuntu 16.04 i have this error with version 0.1.4 while i have no error with version 0.1.3

Any hint?

pkg/prelude/bootstrap.js:1244
      throw error;
      ^

Error: libnode.so.72: cannot open shared object file: No such file or directory
    at Object.Module._extensions..node (internal/modules/cjs/loader.js:1186:18)
    at Module.load (internal/modules/cjs/loader.js:984:32)
    at Function.Module._load (internal/modules/cjs/loader.js:877:14)
    at Module.require (internal/modules/cjs/loader.js:1024:19)
    at Module.require (pkg/prelude/bootstrap.js:1225:31)
    at require (internal/modules/cjs/helpers.js:72:18)
    at bindings (/opt/linux-rpdb-folders/node_modules/bindings/bindings.js:112:48)
    at Object.<anonymous> (/opt/linux-rpdb-folders/node_modules/drivelist/js/index.js:25:27)
    at Module._compile (internal/modules/cjs/loader.js:1136:30)
    at Module._compile (pkg/prelude/bootstrap.js:1281:32)

**Comment by jaruba** [comment]
Try this:
- `sudo apt update`
- `sudo apt install nodejs`

Node.js is the programming language that was used to build the RPRB Folders app.

**Comment by jaruba** [comment]
Also I see that u have one issue for Win and one for Linux. RPDB Folders should work fine with network drives, but using File Systems operations on network storage is generally 10x slower. So it is recommended to use the RPDB Folders app (either the app directly or the Docker image) on the server where the files are hosted for improved speed.

**Comment by memnos** [comment]
> Try this:
> 
> * `sudo apt update`
> * `sudo apt install nodejs`
> 
> Node.js is the programming language that was used to build the RPRB Folders app.

I've got the same error also after this

**Comment by memnos** [comment]
> Also I see that u have one issue for Win and one for Linux. RPDB Folders should work fine with network drives, but using File Systems operations on network storage is generally 10x slower. So it is recommended to use the RPDB Folders app (either the app directly or the Docker image) on the server where the files are hosted for improved speed.

I've got a linux server in my house and my movies on a remote drive mounted with rclone. And i'm using Emby.
I'm trying to understand which is the best solution to use RPDB.
For the beginning i have to convert all the poster and then only new ones.
I tried yesterday to mount my drive in windows not on my server to use RPDB folders, 
And today i tried directly on my linux server, but with this error.

**Comment by jaruba** [comment]
Do you get a result when doing `node -v` in the terminal?

**Comment by memnos** [comment]
Here it is

/opt/linux-rpdb-folders# node -v
v8.10.0

**Comment by jaruba** [comment]
I see that ur Ubuntu version also supports 32bit, they only provide a 64bit version since Ubuntu 19+.

Can you confirm that you are using Ubuntu with the 64bit architecture?

**Comment by jaruba** [comment]
As it was built with Node 12, you should also try this:
- `sudo apt install npm`
- `sudo npm install -g n`
- `n 12`
- `node -v`

This should report that u have switched to Node.js v12, and try to run the RPDB Folders app again. But if you are using Ubuntu 32bit this still won't work, as the app was built for 64bit.

**Comment by memnos** [comment]
I've done what you told but after that i have the same error

/opt/linux-rpdb-folders# npm install -g n
/usr/local/bin/n -> /usr/local/lib/node_modules/n/bin/n
/usr/local/lib
└── n@7.3.0

root@NUC:/opt/linux-rpdb-folders# n 12
  installing : node-v12.22.1
       mkdir : /usr/local/n/versions/node/12.22.1
       fetch : https://nodejs.org/dist/v12.22.1/node-v12.22.1-linux-x64.tar.xz
   installed : v12.22.1 (with npm 6.14.12)

Note: the node command changed location and the old location may be remembered in your current shell.
         old : /usr/bin/node
         new : /usr/local/bin/node
To reset the command location hash either start a new shell, or execute PATH="$PATH"
root@NUC:/opt/linux-rpdb-folders# node -v
v8.10.0

**Comment by memnos** [comment]
> I see that ur Ubuntu version also supports 32bit, they only provide a 64bit version since Ubuntu 19+.
> 
> Can you confirm that you are using Ubuntu with the 64bit architecture?

I'm on 64 bit

**Comment by jaruba** [comment]
that is not an error, it is a note, restarting ur server should load the new node version properly

**Comment by memnos** [comment]
Unluckly reboot didn't solve.
I really don't know how to start rpdb

**Comment by jaruba** [comment]
Give me a few days, I'll solve the issue, I'm out camping so I can't look into it right now.

**Comment by memnos** [comment]
Don't worry, i'll wait

**Comment by jaruba** [comment]
There was indeed an issue with the v0.1.4 linux build. Please confirm that the attached archive works for you on Ubuntu 16.04:
[linux-rpdb-folders.zip](https://github.com/RatingPosterDB/rpdb-folders/files/6736595/linux-rpdb-folders.zip)

**Comment by memnos** [comment]
I can confirm that this built is working fine
