### ISSUE TITLE
[Issue/Bug] Folders with the exact same name, in different media folders, will duplicate poster from each other

### ISSUE THREAD

**Issue by VP-EN** [RatingPosterDB/rpdb-folders#25]
**[Issue/Bug] Folders with the exact same name, in different media folders, will duplicate poster from each other**

**Describe the bug**
If you have two folders with the exact same name, in different media folders, you can't update them separately.

**To Reproduce**

1. Create two folders, one named `4KTV`and `TV Shows`
2. In both of them, create a sample folder with the same name
3. In my case, `Chernobyl (2019) [imdb-tt7366338]`
4. Add both `4KTV` and `TV Shows` to RPDB as TV media folders
5. Let RPDB scan both of them, adding `poster.jpg` to both folders
6. Edit one of the posters through RPDB:  
7. `Edit Series Poster` --> `Search for Folder Name` 
8. Select `4KTV` folder and find the `Chernobyl (2019) [imdb-tt7366338]`
9. Edit some badges in, e.g. make it extra cool with some 4K badges
10. Either the `4KTV` version will get updated, or the one residing in `TV Shows` (or both of them)
11. **In my case**... I'll go and edit the same `Chernobyl (2019) [imdb-tt7366338]`, this time selecting `TV Shows`
12. You'll see the 4K badges present

**Another way of testing this:**
From Step 5:
6. Delete both `poster.jpg`, generated by RPDB
7. Go back to `Edit Series Poster` --> `Search for Folder Name`
8. Select `4KTV` and search for the `Chernobyl (2019) [imdb-tt7366338]` folder
9. Select `Update Ratings` to refresh poster
10. The new `poster.jpg` will be put in the `Chernobyl (2019) [imdb-tt7366338]` folder residing in the `TV Shows` media folder - and **NOT** the `4KTV` media folder. 

**Expected behavior**
The posters getting edited separately and not being of one entitiy / sharing the `poster.jpg`

**Operating System:**
 - OS: Ubuntu 20.04.2 LTS

**Version:**
 - Version v0.1.4

**Comment by jaruba** [comment]
That makes sense, as settings are saved by IMDB ID. I am planning a solution for this, but it might take some time to accomplish.

**Comment by jaruba** [comment]
It should be possible to have multiple folders for the same media and different badges for them now with the automatic badges added to v0.1.7
