### ISSUE TITLE
Alternative Colourful Dolby Vision Badge

### ISSUE THREAD

**Issue by darthShadow** [RatingPosterDB/rpdb-folders#26]
An alternative more colourful badge for Dolby Vision.

**Comment by VP-EN** [comment]
Might be slightly irrelevant, but!
I think the current icon is based on the colors [of the logo](https://cdn2.expertreviews.co.uk/sites/expertreviews/files/styles/er_main_wide/public/7/26//dolby_vision_logo.jpg?itok=Jw_jHuIx)

Previously discussed here: https://github.com/RatingPosterDB/rpdb-folders/issues/12#issuecomment-849029338

**Comment by jaruba** [comment]
I don't mind making another more colourful alternative for the DoVi badge.

**Comment by jaruba** [comment]
@darthShadow thoughts?

![new-badge-test9](https://user-images.githubusercontent.com/1777923/129105016-d903d57e-a385-4698-9ae2-796d7bc3b534.png)

**Comment by darthShadow** [comment]
Perhaps a lighter shade of the colours in the centre so that the text is slightly more visible? The HDRColor badge is spot-on in terms of the contrast between text and the colours so I was looking for something similar. That said, I am not a designer at all so I may be off here :sweat_smile:

**Comment by jaruba** [comment]
@darthShadow I don't particularly like the result either, but the more colors we add, the harder it is to maintain text visibility. I'll think about it more.

**Comment by jaruba** [comment]
@darthShadow how about this?

![new-badge-test14](https://user-images.githubusercontent.com/1777923/129114999-b47483b4-2b8b-412c-b4a2-a3004ffe63b5.png)

**Comment by darthShadow** [comment]
Looks much better.

2 suggestions, if you don't mind:

* How about making the dolby vision logo box fully black the hemispheres as empty rather than the current, where the hemispheres are black but the surroundings are empty. Something like this: https://en.wikipedia.org/wiki/Dolby_Vision#/media/File:Dolby.Vision.Logo.png

* Perhaps also increase the font-weight (or bold) of one of either "Dolby" or "Vision" in the "Dolby Vision" text at the bottom.

**Comment by jaruba** [comment]
@darthShadow 

1. not sure if I understand the first suggestion, if the logo would be black (and the center colored), it would not be visible within the dark background of the badge, and the dark background needs to be there so all the badges can follow the same pattern

2. if u look closely you'll realise that the "vision" word is already bold, while "dolby" is not, I can't make it bolder than that as otherwise it will also break the pattern of the badges.. but again, the more colors we add, the harder it is to notice such details as the gradient / contrast take more of the viewer's attention

**Comment by darthShadow** [comment]
1. I am probably not explaining it properly which is why the linked image shows it better. I basically want it to match the other badges like 4k where the letters "4" & "k" are holes in a black box. I want the oval halves to be the holes here. Currently, it's the inverse with the oval halves being black.

2. Yeah, it's not really discernible, even after you have pointed it out. I was imagining something like the "Ultra HD" text where "HD" is quite clearly bold. But no matter if it breaks uniformity.

**Comment by jaruba** [comment]
@darthShadow you mean like that? I made "dolby" bold and set "vision" to regular, and cut out the centers of the logo, but I have to say, that's not the actual logo of DoVi anymore, and it's strange to use bold on the "dolby" word as that's not the actual feature, it's a company name..

![new-badge-test15](https://user-images.githubusercontent.com/1777923/129117831-7096544b-d134-4616-a02e-cea98b3733c7.png)

**Comment by darthShadow** [comment]
Yep, this is what I meant.

1. Could the ovals be made relatively larger in percentage to the box they are present in? The earlier linked Wikipedia logo has a good ratio of the oval to the containing box.
2. Yeah, Dolby being bold doesn't make sense here. Plus we also have Dolby Atmos. So you can probably revert it back to "Vision" being bold then.

**Comment by jaruba** [comment]
@darthShadow 

![new-badge-test16](https://user-images.githubusercontent.com/1777923/129118865-c8499c13-9725-4417-871d-2167dfa8b08b.png)

**Comment by darthShadow** [comment]
Perfect. Thanks a lot.

Will this be available soon via the API too or only next month?

**Comment by jaruba** [comment]
@darthShadow 

I added them to the API: `dolbyvisioncolor` and `dolbyvisioncoloralt` (the one with "alt" at the end is the one you like more)

It will take more time to add them to the app too.

**Comment by darthShadow** [comment]
Feel free to re-open the issue if you want to keep it till it's added to the app. I closed it because my requirement has been satisfied.

**Comment by jaruba** [comment]
@darthShadow The v0.1.8 version was just released that includes menus in the app's UI to choose these new badges.

**Comment by darthShadow** [comment]
Thanks.
