### ISSUE TITLE
[Bug / Issue] Some HDR (PQ) not detected properly by Automatic Badge probing

### ISSUE THREAD

**Issue by VP-EN** [RatingPosterDB/rpdb-folders#27]
**Describe the bug**
Some HDR is not detected properly, when probing TV series episodes.
This has not happened in my entire movie library, so I'm pretty sure it's specific to WEB based HDR episodes of some TV series.

From my short research, it's the HDR episodes tagged with:
`"transfer_characteristics": "PQ"` in the mediainfo output (JSON).

These episodes containing that PQ string will not get detected as HDR in the rpdb.json generated.

**Logs**
I've found a few series with this issue.. All seem to have the "PQ" thing in common:
TV Series:
```
--> Loki
Generated from S01E01:
Mediainfo Output: https://0bin.net/paste/NaAweyYp#1JPE1wjthnoSND+MDRvRHIOSF1jHezXlD1T8rsnyX4-
rpdb.json Output: https://0bin.net/paste/jZUR4bEa#-OwcDHcRIcpc24Q4JgHjFrozVF1Ik+Why7GKtq13f3N
	
--> The Falcon and the Winter Soldier
Generated from S01E01:
Mediainfo Output: https://0bin.net/paste/vIwNRsgV#IRCIY+Fi4HPDQvsEAtazokSAo2YVAzFb3EPBpWLrcZi
rpdb.json Output: https://0bin.net/paste/8Z5CaHuD#AoWmLL2HFQqRujQTTyXUZov2G-H5YPTyk54UJzjWFTF
	
--> The Mandalorian:
Generated from S01E01:
Mediainfo Output: https://0bin.net/paste/ivIiJ1i3#UUJgsHIWwfNJRySO3qwSI7O3xTbrNZhH8OxL0jdm7BO
rpdb.json Output: https://0bin.net/paste/tyxCoMhr#9oZijvgK21TjFnxGeBqIH4NQjPMRWuU7v7rmKbkTZ5T
	
--> 11.22.63 (non-HDR series to compare)
Mediainfo Output: https://0bin.net/paste/ynVsirIM#8A4rDKHfnI3xPD-GhgkNAj8az52TkavUDi35PR6Y5mE
```

**Expected behavior**
For the rpdb.json to include `"isHdr": true` when it detects "PQ" HDR.
 
**OS:**
```
Distributor ID: Ubuntu
Description:    Ubuntu 21.04
Release:        21.04
Codename:       hirsute
```

**RPDB Version**
- Version v0.1.7

**Additional context**
Thinking the problem is the lack of HDR data for some reason... Except for the "PQ".

Usually it says something about SMPTE or directy  HDR 10 in there.
Not in these files, but Plex registers (correctly) them as HDR.

Sonarr detects them as HDR as well, some relevant code here:
https://github.com/Sonarr/Sonarr/blob/87897d56ea62544a36986eb09d420649668d7400/src/NzbDrone.Core.Test/OrganizerTests/FileNameBuilderTests/FileNameBuilderFixture.cs#L898-L912

Looks like they're going for the "PQ" tag as well.

**Comment by jaruba** [comment]
I also see they all have `"colour_primaries": "BT.2020"`, which is a more common indicator of HDR as far as i know.

**Comment by VP-EN** [comment]
Yeah that would work too I think

**Comment by jaruba** [comment]
Added, it will be available in `v0.1.8`

**Comment by jaruba** [comment]
@VP-EN The v0.1.8 version was just released that includes HDR (PQ) detection.

**Comment by edrock200** [comment]
wait what? RPDB does automatic badge probing? To the wiki-mobile Robin!!!

**Comment by jaruba** [comment]
@edrock200 Edit Media Folder -> (select media folder) -> Add Badges / Labels -> Badge Selection: Automatic
