### ISSUE TITLE
[Feature Request] Video file: .ts support

### ISSUE THREAD

**Issue by VP-EN** [RatingPosterDB/rpdb-folders#28]
[Feature Request] Video file: .ts support

**Is your feature request related to a problem? Please describe.**
Whenever the automatic badge probing looks for videofiles, it "only" checks for the files listed [here](https://github.com/RatingPosterDB/rpdb-folders/blob/main/files.js)

This does not include the weird .ts format, which is sometimes used. Luckily quite rarily.

**Describe the solution you'd like**
To add support for the .ts file format

**Additional context**
Here's a mediainfo output from a sample .ts file:
https://0bin.net/paste/qZUaPwxE#NCrvSk-WttPA+2BT62c7biNW504wp+9QzlPFobZD8MK

**Comment by jaruba** [comment]
That's interesting, I know that `.ts` files are HLS playlist segments, but maybe they are used in other scenarios too. Do u have media that has only one such file for the video? Or multiple such files for the same video? (ie: 1.ts, 2.ts, etc)

**Comment by VP-EN** [comment]
Just only one such file pr movie/video

**Comment by jaruba** [comment]
alright, shouldn't be an issue to add it

**Comment by jaruba** [comment]
Added, it will be available in `v0.1.8`

**Comment by jaruba** [comment]
@VP-EN The v0.1.8 version was just released that includes support for `.ts` video files.
