### ISSUE TITLE
[Feature Request] Timestamps in logs

### ISSUE THREAD

**Issue by VP-EN** [RatingPosterDB/rpdb-folders#30]
[Feature Request] Timestamps in logs

**Is your feature request related to a problem? Please describe.**
Whenever you look at the log file created by `rpdb-folders`, they contain no timestamps.
Having timestamps help with analyzing how long a full scan takes, a full overwrite scan takes, or probing of a large folder.

**Describe the solution you'd like**
It would be nice if the logs contained timestamps. 

**Additional context**
That's it 👍

**Comment by jaruba** [comment]
Makes sense

**Comment by jaruba** [comment]
Added, it will be available in `v0.1.8`

**Comment by jaruba** [comment]
@VP-EN  The v0.1.8 version was just released that includes your requested feature.
