### ISSUE TITLE
Automatic badges and rpdb.json creation

### ISSUE THREAD

**Issue by tscibilia** [RatingPosterDB/rpdb-folders#32]
I just upgraded to tier 3 and I'm having inconsistent results with the automatic badges. I estimate it automatically created about 40% of the files. I'm pretty confident there are no permission issues as the posters are being downloaded to the folders without issue. When the folder scan is active, these are the typical logs I receive: 
`Missing rpdb.json, continuing to probe video file.`
`Poster for Batman Begins (2005) downloaded`
`Items left in queue: 1761`

I'm running rpdb in a docker container & the files are accessed on a network share via NFS mount in that VM. Plex runs on a separate VM & the files are accessed on a network share via CIFS mount. The plex user has read-only access but the docker user has read/write (but I doubt that part matters). All video files are mp4 format.

Let me know if you need more info or have other questions. Alternatively, I could try installing the rpdb plex plugin (instead of docker)

**Comment by jaruba** [comment]
The strange thing here is that 40% of ur library does work.. And there don't seem to be any errors in the logs.

Looking over the code I can see two cases where I haven't made the logic verbose enough. (logs are missing)

1. if the logic is unable to find a relevant video file to probe in the folder (or maybe reading the files within the folder fails)
2. if the rpdb.json file cannot be written inside the directory

Presuming I did not miss any other possible scenarios that are missing logs, and also presuming that there is write access to the folders, (as the poster is written) we should assume that for some reason the application believes that it cannot find a suitable video file within the folders.

A bit more info that would help debug this issue:
- can you play the video files that are missing the probed data in Plex (it is unlikely that these files are corrupted or inaccessible, but it should be checked)
- can u give me a few examples of how the folder / files are structured within your libraries (for both working cases and non-working cases)
Example:
```
- Movies 4K
- - Batman (2005)
- - - Batman.mp4
- - - poster.jpg
- - - Batman.en.srt
```
(the more accurate these examples are, the higher chances that I will be able to reproduce your issues)
- finally, can u try downloading the `mediainfo` application: https://mediaarea.net/en/MediaInfo/Download and running this command from a terminal from one of the remote environments: `mediainfo --output=JSON [video-file-path]` (replacing `[video-file-path]` to the actual path of a video file that did not work as expected) and paste the results in this issue (according to the code, it is unlikely that the file could not be probed without showing something in the logs, but it is best to be sure that this works too)

I do not recommend changing to the Plex plugin, it is far more limited in features and also in the number of available badges, as it is limited by the Plex plugin environment and Plex's own probed data which is not as detailed as the one from the RPDB Folders app.

**Comment by tscibilia** [comment]
Ok all of that is not a problem, but I noticed something I assumed I knew earlier. It seems the video files that don't have the rpdb.json are actually .m4v format. I'm using a [script](https://github.com/mdhiggins/sickbeard_mp4_automator) that converts all videos to mp4 but I guess that all the older videos (before i started using that script) were of a different format. 

Let me know if that helps before I go through documenting all the info you wanted. Also, the videos without the json file are in fact playable. 

[here's an mp4 mediainfo](https://hastebin.com/delilogeka.json)
[here's an m4v mediainfo](https://hastebin.com/terajomiqa.json)

**Comment by jaruba** [comment]
@tscibilia that explains it! the logic is not looking for m4v videos, it can be easily fixed

**Comment by tscibilia** [comment]
So sorry, see what happens when you assume (I thought they were all the same file type). 
Thanks for your quick support!

**Comment by jaruba** [comment]
@tscibilia The v0.1.8 version was just released that should include a solution for your issue. Feel free to re-open this issue if the problem still occurs.
