### ISSUE TITLE
Typo on TrueHD Surround

### ISSUE THREAD

**Issue by tscibilia** [RatingPosterDB/rpdb-folders#33]
I was going through the badges manually and noticed the TrueHD Surround was actually spelled Sorround in both the 5.1 and 7.1 the badges.
![Screenshot 2021-08-11 100839](https://user-images.githubusercontent.com/585808/129044762-ec45966f-9321-4aa0-bf72-15aca2fbe3da.jpg)
![Screenshot 2021-08-11 100816](https://user-images.githubusercontent.com/585808/129044778-25c62a0a-3e04-4817-a445-4808c143a5c4.jpg)

**Comment by jaruba** [comment]
Thank you for noticing and creating an issue for it!

**Comment by jaruba** [comment]
The typos for the 2 badges has been fixed within the API.
