### ISSUE TITLE
IMAX Badge

### ISSUE THREAD

**Issue by darthShadow** [RatingPosterDB/rpdb-folders#36]
Hi,

Could you create a beautiful IMAX badge that can be used for the recently released IMAX cuts of the Marvel movies? I know we can use custom labels but they don't look as good.

Thanks.

**Comment by jaruba** [comment]
Sure, although as far as I understand it, the "IMAX" tag only means that the video has a specific aspect ration (no black bars). Does it mean anything else that I may be unaware of?

**Comment by darthShadow** [comment]
Thanks. No, that's it. It's pretty much just to indicate IMAX-aspect content.

**Comment by jaruba** [comment]
@darthShadow would this suffice?

I'm not sure if it needs anything more extravagant as the feature is just an aspect ratio hint, I tried with the font of the IMAX logo too, but I prefer how the standard badge font looks more tbh.

![new-badge-test21](https://user-images.githubusercontent.com/1777923/141710814-7be9dd75-726e-449a-bf54-980fe943f3a3.png)

**Comment by jaruba** [comment]
New badges that have been added to the API: `imaxgold`, `imax`, `576p`

**Comment by darthShadow** [comment]
That's perfect. Thanks a lot as always for the quick addition.
