### ISSUE TITLE
[Issue] v0.1.1 - Not able to set password - nothing happens.

### ISSUE THREAD

**Issue by VP-EN** [RatingPosterDB/rpdb-folders#4]
**Describe the bug**
I'm not able to set password. When you enter the password in the `Choose Password` and press `Save Password`, nothing happens. Restarting the app does nothing as well.

**To Reproduce**
1. Go to the config page at `X.X.X.X:8750` (remote URL in my case)
2. Click on `Choose Password`
3. Enter your password and press `Save Password`
4. Return to main-page (after pressing `Save Password`)
5. Nothing happens
6. Restart `rpdb-folders`, nothing happens.

**Expected behavior**
The `config.js` should've updated the `"pass":false` to `"pass":true` and the `rpdb-folders` app should've remembered the password I just set.

**Operating System:**
 - OS: Ubuntu 20.04.2 LTS

**Version:**
 - Version v0.1.1
 
**Additional context**
I tried setting the password, updating the `config.js` manually to `"pass":true`. But after reloading the `rpdb-folders`, it didn't recognize the password I just set.

**Comment by jaruba** [comment]
I tested this quite thoroughly, I will try to reproduce it soon to see what might be causing your issues.

If you want to edit `config.json` for this, the value for `"pass"` can be either `false` or your password. Presuming your password is `secret password`, you would need to change `config.json` with:
`"pass": "secret password"`.

**Comment by VP-EN** [comment]
Ah sweet. I'll just do that then :). I tried setting multiple different passwords, restarting each time, but it didn't do much in my case. Not sure what's up with that.

My `config.js` is filled with a bunch of both custom poster urls and imdb fixes.. Not sure if it has anything to do with that. Might work if the `config.js` is as "default" as possible?

**Comment by jaruba** [comment]
I doubt that has anything to do with it, it should not break the config regardless of how large it becomes, it might be something I broke after making that feature, I will check.
