### ISSUE TITLE
Manual Poster upload/creation not working

### ISSUE THREAD

**Issue by edrock200** [RatingPosterDB/rpdb-folders#42]
Hey bud,
Tried to add a custom poster today in two different ways.  Here's what I did to reproduce:
Click Edit Movie Poster
Search for folder name
Find the folder and click it
I then get the page with the "Missing Poster" place holder and the options such as custom poster, create poster etc.

From here, I've tried a few different things:
1. Click Custom poster, paste in a URL for the jpg, and click "Load Poster Image." Nothing happens. I've let it sit here for 5m but it never loads the image. 
2.  Click Create poster - enter image URL then click "Preview Poster" - No image
3. Click Create poster - enter TMDB URL, click preview poster, no image

If I click "Submit" on options 2 or 3, it says thanks for submitting the info to the db. But I cant seem to figure out how to get it to load a poster. Also, theres no way to directly upload a poster file via the web interface, correct?

Thanks in advance,
-Ed

**Comment by jaruba** [comment]
@edrock200 

Hi, I checked your API request limit and you are well within the monthly limits.

I also checked the "Custom poster" feature and it works as expected (on v0.2.4), could it be that the image you tried to add was inaccessible by the RPDB servers? (this might be a likely scenario)

Or maybe the folder was not matched to any IMDB ID? (try using "Fix match" first with a IMDB URL)

Or maybe the IMDB ID has no ratings in RPDB yet? (it won't show a poster, even a custom poster, if it has no ratings to add to the image)

Or maybe some minor temporary outage of the servers? (very unlikely imo)

When using the "Create poster" feature, you need to also provide at least one rating manually (this feature only uses manually added ratings), without any rating set manually, this feature will not show any poster.

**Comment by edrock200** [comment]
> @edrock200
> 
> Hi, I checked your API request limit and you are well within the monthly limits.
> 
> I also checked the "Custom poster" feature and it works as expected (on v0.2.4), could it be that the image you tried to add was inaccessible by the RPDB servers? (this might be a likely scenario)
> 
> Or maybe the folder was not matched to any IMDB ID? (try using "Fix match" first with a IMDB URL)
> 
> Or maybe the IMDB ID has no ratings in RPDB yet? (it won't show a poster, even a custom poster, if it has no ratings to add to the image)
> 
> Or maybe some minor temporary outage of the servers? (very unlikely imo)
> 
> When using the "Create poster" feature, you need to also provide at least one rating manually (this feature only uses manually added ratings), without any rating set manually, this feature will not show any poster.

So I can reproduce this fairly regularly. Heres example steps:
Series "Pieces of Me"
I click Edit Series Poster, search for the folder, and click it, then it opens a page that says "Missing Poster" with the buttons underneath.
I click "Chose Poster"
Load posters, then I click one, and it goes back to the missing poster page. If I click the "Update ratings" button, it says successfully updated, but still says missing poster. For both the poster selection click and the update ratings click, this error is logged in portainer:
`[3/11/2022, 6:43:47 PM] No poster available for Pieces of Her (2022) [imdb-tt9170236] [tvdb-384186]`
Which is odd, because it shows me a list of posters to select from.
Screenshots:
https://imgur.com/yPx4qRF
https://imgur.com/FjK7XGQ

**Comment by jaruba** [comment]
@edrock200 

Hi, thank you for the detailed reply, I can reproduce this issue and it is definitely an issue in the RPDB servers. Items that should have ratings are missing ratings. (the "missing poster" error can hint to either the poster missing, or ratings missing)

I believe I have found the cause of the issue and am working on making the missing posters / ratings available.

**Comment by jaruba** [comment]
@edrock200 

I thought I could reproduce this, but I cannot, this folder name works fine for me: `Pieces of Her (2022) [imdb-tt9170236] [tvdb-384186]`

My only theory is that this item somehow got matched to the wrong ID, can you try using "Fix Match" with a IMDB URL?

**Comment by edrock200** [comment]
> @edrock200
> 
> I thought I could reproduce this, but I cannot, this folder name works fine for me: `Pieces of Her (2022) [imdb-tt9170236] [tvdb-384186]`
> 
> My only theory is that this item somehow got matched to the wrong ID, can you try using "Fix Match" with a IMDB URL?

So when I try that, it acts like it's pulling the right poster, because it shows me per the screenshots above. But when I select it, and go back to the main screen for the options, the poster isn't there. It's like it's not grabbing it. Same thing for if I supply a poster via url. It seems like the manual poster loading in general isn't working and I'm not sure why.

**Comment by edrock200** [comment]
So...just like a car that "won't make the noise" when you go to the mechanic, it's working properly now. Nothing has changed that I'm aware of so no idea why it's working now and not before. I'll keep an eye on it and report back if it happens again. Sorry for wasting your time. I don't know if it matters, but I do have the container behind an nginx-proxy so it can be properly SSL secured. This reverse proxy though has never caused any issues. To clarify, sonarr/radarr talk directly across docker on the native RPDB ports, not through the proxy. The proxy is just for interacting with the web gui. I should have mentioned this early on and it slipped my mind, but I hate it when people ask me to troubleshoot something then leave out some key detail that could affect everything, lol, so my apologies!
