### ISSUE TITLE
Badges on Backgrounds

### ISSUE THREAD

**Issue by jaruba** [RatingPosterDB/rpdb-folders#44]
User suggestion for a new feature, this might take some time as backgrounds did not require any editing until now.

**Comment by edrock200** [comment]
Thanks for the consideration! For others seeing this, the primary reason is Emby uses the background images for "Next up" view.

**Comment by jaruba** [comment]
@edrock200 This has been added in v0.2.7 as an option in the main menu called "Badges on Backdrops", there is an issue with this feature though: currently it will only output backdrops at max 720p, this is a technical limitation and i'm looking into it..

Full release notes for v0.2.7 are here: https://github.com/RatingPosterDB/rpdb-folders/releases/tag/v0.2.7

Please do test this release as there have been some major changes that I don't think were tested very well..

**Comment by edrock200** [comment]
Thank you!!
