### ISSUE TITLE
Permissions on posters.jpg not using container PGID/PUID

### ISSUE THREAD

**Issue by edrock200** [RatingPosterDB/rpdb-folders#45]
Did something change in the last release? I started noticing poster.jpg is owned by user/group root, whereas before it was owned by the PUID/PGID set on the env variables on the container.

**Comment by jaruba** [comment]
@edrock200 Hi, nothing changed in the way that RPDB folders writes files. As the app does not set any file permissions, the files should be created with the same user permissions that are set for the app itself when it is ran.

When using badges though, the app needs to have access to read the video files, as otherwise it cannot analyse them for the badges feature.

I remember you said you started using badges recently, maybe you started the app as root when enabling the badge feature?

**Comment by edrock200** [comment]
I didn't. I run it as a docker container. The docker container respects the pgid and puid env values on the container correct? Either way if you didn't change anything it must be something on my end. I'll dig into it. Thanks bud!

**Comment by edrock200** [comment]
@jaruba what base image do you use for your docker image? Do you have a docker compose you'd be willing to share? (Or if it's already published point me to the file please ) Want to run some tests on this permissions thing. As far as I can tell the container doesn't seem to be respecting the puid and pgid env variables. Not sure if it's image specific or what.

**Comment by jaruba** [comment]
@edrock200 i use it in docket with based on the example from: https://github.com/RatingPosterDB/rpdb-folders-docker/blob/main/README.md

I don

**Comment by jaruba** [comment]
I'm currently away on vacation until the 30th of May, and will be on a 2 day business trip after that.

I'll set a reminder for myself to check my installation when I get home on the 30th, but i realistically don't remember setting any specific permissions for the docker container. (also using it on Linux)

**Comment by edrock200** [comment]
No worries bud! Enjoy your well deserved vaca! This isn't urgent at all.

**Comment by edrock200** [comment]
Hey bud, no worries on this. I was able to resolve. I forked your Dockerfile and added this line before the last "npm start" line, and now it's writing as UID 1000 :)
```USER 1000
CMD ["npm", "start"]```

**Comment by edrock200** [comment]
Cool. I'm not too familiar with GitHubs workflows but I'll test this out for a few days first and if no issues, I'll try to create one.
