### ISSUE TITLE
Have movie/show edit search results display full path with line wrap

### ISSUE THREAD

**Issue by edrock200** [RatingPosterDB/rpdb-folders#47]
Feature suggestion - when having multiple versions of the same movie in different root paths, e.g. HD, 4K, it can be difficult to know which search results is which if the movie or show folder is named the same. Suggesting adding full path for results, with line wrap for ease of use on mobile. Thanks for the consideration!

**Comment by jaruba** [comment]
Hi, I will try to think of the best way to handle this case.

**Comment by jaruba** [comment]
This has been added in v0.2.7 by showing the parent folder between brackets at the end of the search results.

Full release notes for v0.2.7 are here: https://github.com/RatingPosterDB/rpdb-folders/releases/tag/v0.2.7

**Comment by edrock200** [comment]
I noticed! Thank you!!
