### ISSUE TITLE
[Issue] v0.1.1 - RPDB Config page shows "A new update is available", while latest version is installed.

### ISSUE THREAD

**Issue by VP-EN** [RatingPosterDB/rpdb-folders#5]
**Describe the bug**
After installing v0.1.1, the rpdb config page at `X.X.X.X:8750` still shows up with a message, saying 
`A new update is available, download it here!`. Even after installing the `rpdb-folders` version it redirects to, the same message still shows.

**To Reproduce**
1. Download v0.1.1 for Linux through the [Github Release page](https://github.com/RatingPosterDB/rpdb-folders/releases/tag/v0.1.1)
2. Go to the rpdb config-page at `X.X.X.X:8750` (remote URL in my case)
3. See the `A new update is available, download it here!` prompt
4. Download the version it redirects to
5. Remove the old linux-rpdb-folders: `rm -rf linux-rpdb-folders`
6. Unzip the new one: `unzip linux-rpdb-folders.zip`
7. Run the `rpdb-folders` app 
8. Same message appears: `A new update is available, download it here!`

**Expected behavior**
After applying / running the latest version of `rpdb-folders`, the message should not appear.

**Screenshots**
https://i.imgur.com/YTatzqa.png

**Operating System:**
 - OS: Ubuntu 20.04.2 LTS

**Version:**
 - Version v0.1.1
 
**Additional context**
Nothing to add for now.

**Comment by jaruba** [comment]
This is definitely my fault, Linux should be the only one that has this issue, I'll release a new version this weekend with a fix.

**Comment by VP-EN** [comment]
> This is definitely my fault, Linux should be the only one that has this issue, I'll release a new version this weekend with a fix.

Thank you! It's a minor thing :)
Might want to add some version display on the main config page, like at the bottom or so. So that the user knows what version they're running, e.g. "rpdb-foldrs v0.1.1"

**Comment by jaruba** [comment]
I believe it should work with the v0.1.2 release
