### ISSUE TITLE
Missing Poster

### ISSUE THREAD

**Issue by jaydecay78** [RatingPosterDB/rpdb-folders#53]
Hi, having an issue the last few days that posters dont load or download - just get the greyed out missing poster image.

It seems to load the first time but if I try to change or add labels just takes ages then displays no poster found image 

Is doing for movies and TV series

![image](https://github.com/RatingPosterDB/rpdb-folders/assets/111127502/7a040c22-6bef-4629-9f72-6d058f2b602c)

**Comment by jaruba** [comment]
Hi, thank you for reporting this, I believe it should be working now. Please inform me if you encounter any further issues.

**Comment by jaydecay78** [comment]
Thank you that's done the trick 😊

**Comment by jaruba** [comment]
I'm happy it's working as expected
