### ISSUE TITLE
[Feature Request] Go back one level/step in the "Edit Movie/Series Poster" menu

### ISSUE THREAD

**Issue by VP-EN** [RatingPosterDB/rpdb-folders#6]
**[Feature Request] Go back one level/step in the "Edit Movie/Series Poster" menu**

**Is your feature request related to a problem? Please describe.**
When editing multiple posters using either the `Edit Movie Poster` or `Edit Series Poster` menus, it can be a bit time consuming having to return to the main configuration page, after pressing "Close", after editing a poster.

**Describe the solution you'd like**
It would be nice to have a "back-one-step" button. 
So instead of returning to the main configuration page, after pressing `Close`, it would be nice to have a `Back` button, which would return to the folder overview (the one you enter at first, when pressing either `Edit Movie Poster` or `Edit Series Poster`).

**Additional context**
So it could work like:
1. Press `Edit Movie Poster`
2. Enter the `Search Movie Folders` menu
3. Find the specified movie folder
4. Edit whatever you need to, e.g. `Fix Match`
5. Press `Back` and return to the `Search Movie Folders` overview.

**Comment by jaruba** [comment]
Thank you for creating an issue for this, I will add a "back" button to the edit poster menu.

**Comment by VP-EN** [comment]
Much love mate. Thanks for the quick responses

**Comment by jaruba** [comment]
This has been added to v0.1.2
