### ISSUE TITLE
[Feature Request] Edit Movie/Series Poster in Media Folder of choice

### ISSUE THREAD

**Issue by VP-EN** [RatingPosterDB/rpdb-folders#7]
**[Feature Request] Edit Movie/Series Poster in Media Folder of choice**
Hey again, sorry for spamming up your Github issue page. 
Just realized another thing, which could be useful.

**Is your feature request related to a problem? Please describe.**
Whenever you want to edit either a movie poster or series poster, you have to search all "Movie" media folders and/or all "Series" media folders at the same time.
This can be a problem because of duplicates. E.g. if you have a `4K Movie` folder, `4K Remux` folder, `1080p` Folder and so on. They'll probably have the same movie/series folder names, and it'll be hard to distinguish between which one's which. You might want to have different posters for each library, or just for "OCD" purposes, have them seperated.

**Describe the solution you'd like**
It would be nice, **if** you have multiple `Movies` (or `Series`) media folders, that you could select between the different Media folders, before searching. 

**Additional context**
E.g.
1. Press `Edit Movie Poster`
2. In there, add an option to `Choose Media Folder`
2.1 Could be the same layout as the `Edit Media Folders` page
3. From there, search within that chosen `Media Folder`
4. Avoid duplicates, be awesome, find poster, edit whatever, exit

**Comment by jaruba** [comment]
I see the usefulness of this feature, I'll add it.

You are not spamming the GitHub repo, I'd prefer it if I would get more issues / features here tbh, as most come from all over the place (email, reddit, patreon, etc.) and they can be hard to track that way.

**Comment by jaruba** [comment]
This feature has been added to v0.1.2
